from . import kb_document_type
from . import kb_application
from . import kb_application_document_template
from . import kb_application_stage
from . import kb_class
from . import kb_class_history
from . import kbw_class_history_create
from . import kb_school
from . import kb_student
from . import kb_student_document
from . import kb_term
from . import res_config_settings